### LOCAL - ping
GET http://localhost:8000/ping

### LOCAL - titanic/model
POST http://localhost:8000/titanic/model
Content-Type: application/json

{
    "request_id": "16fd2706-8baf-433b-82eb-8c7fada847da",
    "data": [
        {
            "passenger_id": "A00001",
            "sex": "male",
            "sib_sp": 0,
            "parch": 0,
            "fare": 15.0,
            "embarked": "S",
            "p_class": "2"
        },{
            "passenger_id": "A00002",
            "sex": "female",
            "sib_sp": 2,
            "parch": 1,
            "fare": 30.0,
            "embarked": "S",
            "p_class": "1"
        }
    ] 
}